name: Publish package to the Maven Central Repository and GitHub Packages
on:
  release:
    types: [created]
jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [ 8, 11 ]
    env:
      OS: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  publish_github:
    runs-on: ubuntu-latest 
    needs: build
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# wouldn't work with maven central as github wouldn't pack javadocs and sources...
# need to figure that out ... released manually
#
#  publish_maven_central:
#    runs-on: ubuntu-latest
#    needs: build 
#    permissions: 
#      contents: read
#      packages: write 
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Java for publishing to Maven Central Repository
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          server-id: ossrh
#          server-username: MAVEN_USERNAME
#          server-password: MAVEN_PASSWORD
#          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
#          gpg-passphrase: MAVEN_GPG_PASSPHRASE
#      - name: Publish to the Maven Central Repository
#        run: mvn --batch-mode -P mavenCentral deploy
#        env:
#          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
#          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
